# Generated by Django 3.2.9 on 2021-11-18 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_alter_dish_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='cuisine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='foodapp.cuisine'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
