# Generated by Django 3.2.9 on 2021-11-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_auto_20211119_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
